spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_management_system
    username: postgres
    password: 1232002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    show-sql: true

server:
  port: 8080

jwt:
  secret: 1232002
  expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#    operationsSorter: alpha
#    tryItOutEnabled: true
#    validatorUrl: null
